name: Mirror ROM to Google Drive
on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'URL file ROM'
        required: true
        type: string

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Optimasi Storage Runner
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Unduh File ROM
        run: |
          mkdir -p downloads
          echo "Mengunduh dari: ${{ github.event.inputs.rom_url }}"
          wget -P downloads/ --content-disposition --no-check-certificate "${{ github.event.inputs.rom_url }}"

      - name: Setup Rclone dan Upload ke Google One
        env:
          RCLONE_SECRET: ${{ secrets.RCLONE_CONF }}
        run: |
          # 1. Buat folder konfigurasi
          mkdir -p ~/.config/rclone
          
          # 2. Masukkan secret ke dalam file conf secara aman
          echo "$RCLONE_SECRET" > ~/.config/rclone/rclone.conf
          
          # 3. Instal Rclone
          sudo apt update && sudo apt install rclone -y
          
          # 4. Eksekusi Upload
          echo "Memulai unggah ke Google Drive..."
          rclone copy downloads/ gdrive:Mirror_ROM/ -v --stats 5s
